language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - python config.py --debug
  - python manage.py migrate
  - python manage.py loaddata fixture_sites.yaml
script:
  - python manage.py test
